// <auto-generated />
using System;
using CrusadeTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrusadeTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312155346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrusadeTracker.Domain.Battles.Battle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Battles", (string)null);
                });

            modelBuilder.Entity("CrusadeTracker.Domain.Forces.CrusadeForce", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PointsLimit")
                        .HasColumnType("int")
                        .HasColumnName("PointsLimit");

                    b.Property<string>("_battles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BattleIds");

                    b.HasKey("Id");

                    b.ToTable("CrusadeForces", (string)null);
                });

            modelBuilder.Entity("CrusadeTracker.Domain.Forces.CrusadeUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DataSheet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("int")
                        .HasColumnName("ExperiencePoints");

                    b.Property<Guid?>("ForceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("Points");

                    b.Property<string>("_battleHonours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BattleHonours");

                    b.Property<string>("_battleScars")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BattleScars");

                    b.HasKey("Id");

                    b.HasIndex("ForceId");

                    b.ToTable("CrusadeUnits", (string)null);
                });

            modelBuilder.Entity("CrusadeTracker.Domain.Battles.Battle", b =>
                {
                    b.OwnsMany("CrusadeTracker.Domain.Battles.BattleParticipant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BattleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ForceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ForceNameSnapshot")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Result")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("BattleId");

                            b1.ToTable("BattleParticipants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BattleId");
                        });

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("CrusadeTracker.Domain.Forces.CrusadeUnit", b =>
                {
                    b.HasOne("CrusadeTracker.Domain.Forces.CrusadeForce", null)
                        .WithMany("Units")
                        .HasForeignKey("ForceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CrusadeTracker.Domain.Forces.CrusadeForce", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
