services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: crusadetracker-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=CrusadeTracker!Dev123
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
